stuartjamesmcnicholas/Moorhen

.github/workflows/main.yml

This will run the tests every day at midnight on the latest commit. Currently fails at `emmake make` stage but once the undefined reference from coot is patched then it should be fine.

Enable CI with github actions

---

react-app/src/FlipPeptide.js
react-app/src/Main.js
react-app/src/Ramachandran.js
react-app/src/ResidueData.js
react-app/src/ResidueList.js
react-app/src/ResidueMapData.js
web_example/crystallography_worker.js

This update closes #3 
It includes the following changes:
- Removed last traces of `sharedArrayBuffer`.
- Using JSDoc markup language to start documenting functions. I know in some cases the usage of the function is quite obvious but I think it would be good to start using this to document code.
- Widgets now post messages to crystallographby worker via promises.
- Widgets post messages consisting of objects rather than arrays. I feel this will keep the code more tidy as it will be very easy to refactor code in the future to add more attributes to these messages in future updates rather than having to keep track of array indices. What do you think?
- Using `async...await` syntax to deal with promises.

Use promises to comunicate between widgets and cryst worker

---

react-app/src/Main.js
react-app/src/Ramachandran.js
react-app/src/ResidueData.js
react-app/src/ResidueList.js
react-app/src/ResidueMapData.js
web_example/crystallography_worker.js

This avoids using `Main.js` to update the plots. I think we cannot get totally get rid of `dataObjectNames` as the widgets use it to get the `pdbKey` and `mapKey` of the selected model and map. It also gets used in the `render()` method. Not sure if this update is exactly what you had in mind?

Pass results from crystWorker straigth into widgets

---

baby-gru/src/components/BabyGruMolecule.js
baby-gru/src/components/BabyGruRamachandran.js
baby-gru/src/components/BabyGruSequenceViewer.js
react-app/src/Ramachandran.js
react-app/src/SequenceViewer.js

Sorry this was meant to go in the previous PR. I've enabled the `selection` argument in  `BabyGruMolecule.centreOn`. I am not sure if this is what @martinemnoble1 had in mind when writing this, but with this implementation `selection` would be expected to be an object with the attributes `modelIndex` `molName` `chain` and `seqNum`. This change means less code repetition between `BabyGruRamachandran` and `BabyGruSequenceViewer`.

Refactor ramaplot and seqViewer to use the same methd to centre on residues

---

baby-gru/public/CootWorker.js
baby-gru/src/components/BabyGruDisplayObjects.js
baby-gru/src/components/BabyGruMolecule.js
web_example/coot_example.cc

This update fixes fragment copy (it was missing a function in the last PR). Also, copied fragments will be assigned a sequence corresponding to the observed residues using the api function `get_single_letter_codes_for_chain`. As suggested, to do this a new `returnType` has been defined and `commandCentre.cootCommand` is being used. There is one issueat the moment: the current sequence viewer assumes that the residue numbering starts at 1, which is not always the case specially when dealing with a copied fragment. Because of this, residue selection using the sequence viewer on the copied fragment doesn't work. This issue is external to the sequence viewer itself, at the moment the object `BabyGruMolecule.cachedAtoms.sequences` does not inform of residue numbering. We might need to think …

Assing sequence to copied fragments

---

baby-gru/public/CootWorker.js
baby-gru/src/components/BabyGruDisplayObjects.js
baby-gru/src/components/BabyGruMolecule.js
baby-gru/src/components/BabyGruRamachandran.js
baby-gru/src/components/BabyGruSequenceViewer.js
web_example/coot_example.cc

This update enables molecule deletion. This is done in the following order:
1. Remove molecule from `props.molecules`. This has a knock-on effect on the children components `BabyGruRamachandran` and `BabyGruSequenceViewer` which have hooks listening to `props.molecules` and would break because it is now null/undefined. Because of this, some hooks had to be updated to check if `props.molecules[selectedModel]` and `sequenceRef.current` are defined. Is there a cleaner way of doing this @stuartjamesmcnicholas / @martinemnoble1 ?
4. Hide all display objects related to the current molecule. I am also not sure if this is the best way to do this, by hiding the display objects are we really removing this from the memory or is it still stored somewhere and they are just not visible?
5. Remove …

Enable molecule deletion

---

baby-gru/src/components/BabyGruDisplayObjects.js

Sorry this was meant to go inside the last PR. This puts the map contour sliders in the same row.

Map sliders in the same row

---

baby-gru/src/components/BabyGruMenuItem.js
baby-gru/src/components/BabyGruMoleculeCard.js

This fixes the issue where after deleting a molecule the molecule cards that are left show the wrong molecule names. Also, code used to delete and rename molecules has been refactored to use `BabyGruMenuItem`.

Fix molecule card deletion bug

---

baby-gru/src/components/BabyGruContainer.js
baby-gru/src/components/BabyGruFileMenu.js
baby-gru/src/components/BabyGruLigandMenu.js
baby-gru/src/components/BabyGruMapCard.js
baby-gru/src/components/BabyGruMenuItem.js
baby-gru/src/components/BabyGruMoleculeCard.js
baby-gru/src/components/BabyGruViewMenu.js

Same PR as before, but after solving merge conflicts. With this update, the dropdown menus will not close when the user clicks inside the input forms in the popovers. If the popover is closed, the expected behaviour is maintained (i.e. close dropdown when user clicks outside). Now it si also possible to rename maps, and code to rename/delete molecules and maps has been refactored to use the same shared components.

 Do not close dropdown menu if popover is open no. II

---

baby-gru/src/components/BabyGruMenuItem.js

This piece of code got lost during the merge conflict and it is essential for the effect to work every time no matter how fast you switch between menus.

Execute setPopoverIsShown before exiting

---

baby-gru/src/components/BabyGruContainer.js
baby-gru/src/components/BabyGruFileMenu.js
baby-gru/src/components/BabyGruHistoryMenu.js
baby-gru/src/components/BabyGruLigandMenu.js
baby-gru/src/components/BabyGruMenuItem.js
baby-gru/src/components/BabyGruValidation.js
baby-gru/src/components/BabyGruViewMenu.js

After #39, if a popover is shown and the user clicks in a different dropdown, the popover will close but not the previous dropdown. This update fixes this and refactors some code.

Only show one dropdown at a time even when popover is shown

---

baby-gru/src/components/BabyGruChainSelect.js
baby-gru/src/components/BabyGruMapSelect.js
baby-gru/src/components/BabyGruMoleculeSelect.js
baby-gru/src/components/BabyGruRamachandran.js
baby-gru/src/components/BabyGruValidation.js

This creates two new selectors `BabyGruMapSelect` and `BabyGruChainSelect`. The latter will inspect the selected model and fill up the list of options with the available chains. Ramachandran plot has been updated to use these new selectors.

Rama plot to inspect chains in selected molecule

---

baby-gru/src/components/BabyGruMapCard.js
baby-gru/src/components/BabyGruMoleculeCard.js

Small update to the buttons on the molecule and the map cards:
- Molecule button to hide molecule representation
- Download buttons have been moved to dropdown menu
- Fixed bug where map download failed
- Re-arranged button order as requested
- Show/Hide map button icons were inverted

Small update to display cards

---

baby-gru/src/components/BabyGruContainer.js
baby-gru/src/components/BabyGruMapCard.js
baby-gru/src/components/BabyGruMoleculeCard.js
baby-gru/src/components/BabyGruPreferencesMenu.js
baby-gru/src/components/BabyGruSequenceViewer.js
baby-gru/src/components/BabyGruSlider.js
baby-gru/src/utils/BabyGruUtils.js

This update includes the following:
- Fix for the bug where the whole app crashes if the molecule passed to the sequence viewer doesn't have a valid sequence.
- The number of buttons that are shown using icons on the top of the molecule and map cards is set dynamically depending on the available space. Those buttons that don't fit end up in the dropdown menu. This improves the code in  #52 where the layout was set to either "expanded" or "collapsed".
- Created a preferences menu in the navbar. At the moment there are only two options: light/dark mode and expand/collapse molecule and map cards after reading a file.

Fix sequence viewer bug and update UI

---

baby-gru/src/App.js
baby-gru/src/components/BabyGruContainer.js
baby-gru/src/utils/BabyGruPreferences.js

This implements persistent preferences stored in the browser's local storage (uses indexed DB if available otherwise plain local storage). Preferences are passed to the different components in the app using `React.createContext` and `React.useContext`. The way it has been written, I think it should be easy to scale up this context provider with more items if necessary in the future.

Persistent preferences

---

baby-gru/src/components/BabyGruContainer.js
baby-gru/src/components/BabyGruKeyboardAccelerators.js
baby-gru/src/components/BabyGruWebMG.js
baby-gru/src/utils/BabyGruPreferences.js
react-app/src/mgWebGL.js

With this update the keyboard accelerators are unified within `BabyGruPreferences` and most of them are handled within `BabyGruKeyboardAccelerators`. However: 
- The main bodies of some functions (move up/down left/right and take screenshot) are still located within `mgWebGL`. At the moment, this works by just calling these functions in `BabyGruKeyboardAccelerators`. I can refactor the whole functions into `BabyGruKeyboardAccelerators` but I thought it would be tidier to keep all the `vec3` and `quat4` stuff within `mgWebGL`. Let me know if you think otherwise. In contrast, I did refactor all of the "go to blob" and "clear labels" code into `BabyGruKeyboardAccelerators`.
- Holding "m" and clicking on a residue is being taken care of within `mgWebGL`. To do this the attribute …

Unify keyboard accelerators

---

baby-gru/src/utils/BabyGruPreferences.js

In this update:
- Stored preferences have a version number. If the version number is different to that of the stored data, the default values are used. This will prevent users having to clear their cache/storage after an update.
- Use `Ctrl` to show toast with list of shortcuts. @martinemnoble1 you proposed using `Shift` to do this but then it would clash with the rotate -Z function. Can I propose to use `Ctrl` instead?
- Use `z` to wiggle camera while fitting a ligand. I could not test this myself @stuartjamesmcnicholas as I'm not sure what is the exact intended use of this shortcut but I think it _**should**_ work.

Updates to stored preferences

---

baby-gru/src/components/BabyGruButtonBar.js
baby-gru/src/components/BabyGruPreferencesMenu.js
baby-gru/src/utils/BabyGruPreferences.js

After this update, a new item is added to the preferences menu which lets users choose whether they want to perform triple refinement after every modification.

Enable automatic post-modification triple refinement

---

baby-gru/src/components/BabyGruButtonBar.js
baby-gru/src/components/BabyGruContainer.js

After this update the button bar on the bottom of the screen will become a carousel. As we add more buttons it could become problematic to fit all of them into a single bar specially in small displays, so this takes care of it by fitting buttons into different carousel items depending on the available space (sensitive to screen re-size). I'm not sure if this is the best solution from the UI perspective so this is also a bit of an experiment, I would like to know what people think about it. The change is easy to revert anyway.

Fit buttons on the bottom bar into a carousel

---

baby-gru/src/components/BabyGruButtonBar.js

This fixes a bug I have recently discovered: if a given edit button is no longer active, the event listener waiting for the user to pick up an atom is not removed. It only gets removed if the user clicks again on the same button to deactivate it. If, instead, the user clicks on a different button while the previous one was still active, the second button then becomes active, and there are two even listeners added. By putting this inside a hook with a cleanup function this is fixed. It also prevents multiple buttons being active at once is the user switches between different carousel items.

Fix button bar bug

---

baby-gru/src/components/BabyGruDifferenceMapPeaks.js
baby-gru/src/components/BabyGruPepflipsDifferenceMap.js
baby-gru/src/components/BabyGruToolsAccordion.js

This implements a pepflips widget. At the moment it won't show anything as the api function `pepflips_using_difference_map()` returns an empty array for the data in tutorial 1, but I have tested this with other functions that also return a vector of `interesting_place_t` and the code in this widget works as intended. The widget should be able to display the correct data as soon as we fix the problem with the api function (either there's something wrong in libcoot or in the way I call the function).

Pepflips widget

---

baby-gru/src/components/BabyGruPreferencesMenu.js
baby-gru/src/components/BabyGruWebMG.js
baby-gru/src/utils/BabyGruPreferences.js

As requested by @martinemnoble1 I've added the option to draw crosshairs and missing loops into the preferences container. These new preferences are passed to `mgWebGL` via props from `BabyGruWebMG`.

Add preferences to draw crosshairs and missing loops

---

baby-gru/src/components/BabyGruContainer.js
baby-gru/src/components/BabyGruMenuItem.js
baby-gru/src/components/BabyGruMoleculeCard.js
baby-gru/src/components/BabyGruSequenceViewer.js

This fixes two bugs:
- Ramachandran plot not working due to `hoveredAtom` missing from props.
- The residue range selected with the sequence viewer did not clear after selecting a new residue outside the range.

Fix three minor bugs and merge molecules from molecule card

---

baby-gru/src/components/BabyGruMoleculeCard.js
baby-gru/src/components/BabyGruPreferencesMenu.js
baby-gru/src/components/BabyGruSequenceViewer.js
baby-gru/src/utils/BabyGruPreferences.js
react-app/src/Ramachandran.js

After this update the sequence viewer will be connected to `hoveredAtom`. This means hovering over a residue in the sequence viewer, the ramachandran plot or in the visualisation panel will highlight that same residue in all three components. In this new sequence viewer, hovered residues are highlighted in yellow, which means an alternative visual clue had to be used for residues and ranges of residues clicked in the sequence viewer (these are used as input for "copy fragment" and "refine residue range"). Since it is not possible to have multiple separate ranges of residues with different colours highlighted in `protvista-sequence`, this is now done using an additional `protvista-track` to highlight selected residues.

Connect sequence viewer with hoveredAtom and add mapLineWidth to preferences

---

baby-gru/src/components/BabyGruDifferenceMapPeaks.js
baby-gru/src/components/BabyGruPepflipsDifferenceMap.js
baby-gru/src/components/BabyGruValidation.js

- Validation widget is now connected with `hoveredAtom` just like the other widgets.
- Peptide flip widget is fixed and it shows now a list of peptides. The cards include a "View" button and a "Flip" button.
- Actual peak rmsd is shown when hovering over bars in the difference map peaks widget.

Fix pepflip widget and other UI changes

---

baby-gru/src/components/BabyGruButtonBar.js
baby-gru/src/components/BabyGruContainer.js
baby-gru/src/components/BabyGruEditMenu.js
baby-gru/src/components/BabyGruMapCard.js
baby-gru/src/components/BabyGruMenuItem.js
baby-gru/src/components/BabyGruMoleculeCard.js
baby-gru/src/utils/BabyGruMolecule.js
coot/moorhen-wrappers.cc
react-app/src/mgWebGL.js

- A fix for the "Edit" dropdown button which can now be dismissed by clicking outside the panel as long as the popover is not shown.
- A new item in the molecule card options dropdown to set the new coot bond options
- Merge molecules has been removed from the molecule card options dropdown as this is now included in the "Edit" menu.

Add coot bond options and other UI fixes

---

baby-gru/src/components/BabyGruFileMenu.js
baby-gru/src/components/BabyGruLigandMenu.js
baby-gru/src/components/BabyGruMoleculeCard.js
baby-gru/src/utils/BabyGruMolecule.js

After this update it becomes possible to store a session in the form of a json file. That json file can then be uploaded to re-store the session (includes molecule representation and camera details). This does not include map data yet, this will come in future updates.

Enable session download and upload

---

baby-gru/src/utils/BabyGruMolecule.js
baby-gru/src/utils/BabyGruUtils.js

After this update, `BabyGruMolecule` has a new attribute `gemmiStructure` that stores a `gemmi::Structure`. This gemmi instance is updated inside the method `BabyGruMolecule.updateAtoms` along with `BabyGruMolecule.cachedAtoms`. This means these two attributes should always contain data matching the same molecule (always up to date).

Add gemmi structure to BabyGruMolecule

---

baby-gru/src/components/BabyGruFileMenu.js
baby-gru/src/components/BabyGruLigandList.js
baby-gru/src/components/BabyGruMoleculeCard.js

After this update the contents of the molecule card are organised into an accordion. This can be useful when loading structures with a large number of ligands and/or sequences. Also, after this update, difference maps are also pulled from PDB-REDO.

Convert molecule card into accordion

---

baby-gru/src/components/BabyGruDifferenceMapPeaks.js
baby-gru/src/components/BabyGruLigandList.js
baby-gru/src/components/BabyGruMapSelect.js
baby-gru/src/components/BabyGruMenuItem.js
baby-gru/src/components/BabyGruMoleculeCard.js
baby-gru/src/components/BabyGruPepflipsDifferenceMap.js
baby-gru/src/utils/BabyGruMap.js

After this update, the menu item to connect updating maps is simplified. In essence, the corresponding column labels are asked when the MTZ file is uploaded and the reflection data is parsed accordingly. This way, when the user wants to connect updating maps,  there's no need to re-upload data.

Simplify UI to connect updating maps

---

baby-gru/.babelrc
baby-gru/SimpleCrossOriginServer.py
baby-gru/cloud/index.html
baby-gru/cloud/index.js
baby-gru/package.json
baby-gru/webpack.config.js

This adds a new directory with the index files for CCP4 cloud and a new option to `package.json`. The app can be built using `npm run build-cloud` and the resulting `dist` folder "should" be usable within cloud. There's a wrapper class `MoorhenWrapper` that controls the app, at the moment it only accepts input files.

Create app build compatible with CCP4 cloud using webpack

---

baby-gru/src/components/MoorhenChainSelect.js
baby-gru/src/components/MoorhenContainer.js
baby-gru/src/components/MoorhenMenuItem.js
baby-gru/src/components/MoorhenMoleculeCard.js
baby-gru/src/components/MoorhenSearchBar.js
baby-gru/src/components/MoorhenValidation.js
baby-gru/src/utils/MoorhenMolecule.js
baby-gru/src/utils/MoorhenUtils.js

After this update, `gemmi` is used to get the sequence of the chains in a given molecule. Components have been updated to read this data instead of the one parsed using `mgMinMol.js`.
This update also includes:
- A spinner covers the whole screen when the app starts for the first time until coot is initialised to prevent the user from attempting to load data.
- Moorhen logo replaces the word "Moorhen" in the navbar (this will be available as soon as the logo makes it to pixmaps)
- Button to show/hide the search bar has been included.

Use gemmi to get molecule sequenec and other changes

---

baby-gru/src/components/MoorhenContainer.js
baby-gru/src/components/MoorhenHelpMenu.js
baby-gru/src/components/MoorhenMenuItem.js
baby-gru/src/components/MoorhenMoleculeCard.js
baby-gru/src/components/MoorhenMoleculeCardButtonBar.js
baby-gru/src/components/MoorhenSearchBar.js
baby-gru/src/utils/MoorhenMolecule.js

After this update, rotate/translate molecule gets moved to the dropdown menu in the molecule card. This dropdown menu is now scrollable (it was getting too big). Also, a ghost molecule is shown and the user can accept/reject the transformation.

Moved rotate/translate molecule

---

baby-gru/src/utils/MoorhenMolecule.js
baby-gru/src/utils/MoorhenUtils.js

After this update gemmi is used to draw coot representations instead of `mgMinMol` cached atoms

Use gemmi to draw coot representations

---

baby-gru/src/ErrorBoundary.js
baby-gru/src/components/MoorhenHistoryMenu.js
baby-gru/src/index.js
baby-gru/src/utils/MoorhenUtils.js

This update adds an error boundary to the app. In the event of an unrecoverable app crash, a modal is displayed informing the user and with the option to download all log messages recorded so far.

Add error boundary

---

baby-gru/cloud/index.js
baby-gru/src/components/MoorhenFileMenu.js
baby-gru/src/components/MoorhenHistoryMenu.js
baby-gru/src/components/MoorhenMenuItem.js
baby-gru/src/components/MoorhenMoleculeCard.js
baby-gru/src/utils/MoorhenMolecule.js

After this update, we will stop generating MGWebGL cachedAtoms.

Remove webMGAtoms

---

coot/CMakeLists.txt

So now, there can be gui control over the creation of backups.
Also, there is now infrastructure for the instanced bonds mesh. Not perfect I'd guess, orientation matrices may need to be adjusted.

Add api/coot_molecule_backup.cc to and api/coot_molecule_bonds_instanced.cc the build

---

baby-gru/src/components/MoorhenMenuItem.js
baby-gru/src/utils/MoorhenMolecule.js

This deletes gemmi atoms generated by `MoorhenMolecule.gemmiAtomsForCid` after we are done using them

Delete selected atoms after we are done with them

---

baby-gru/public/baby-gru/CootWorker.js

This fixes memory leaks in the following cootworker methods:
- `simpleMeshToMeshData`
- `floatArrayToJSArray`
- `stringArrayToJSArray`
- `residueCodesToJSArray`
- `validationDataToJSArray`
- `interestingPlaceDataToJSArray`
- `ramachandranDataToJSArray`

Fix multiple memory leaks in cootworker

---

baby-gru/src/components/MoorhenButtonBar.js
baby-gru/src/components/MoorhenMapCard.js
baby-gru/src/components/MoorhenMoleculeCard.js

This reduces the number of warnings printed in the console by assigning unique `key` prop values to some components inside lists.

Fix unique key props warning

---

baby-gru/src/components/MoorhenFileMenu.js
baby-gru/src/components/MoorhenMapCard.js
baby-gru/src/components/MoorhenMenuItem.js
baby-gru/src/components/MoorhenMoleculeCard.js
baby-gru/src/components/MoorhenPreferencesMenu.js
baby-gru/src/components/MoorhenSlider.js
baby-gru/src/utils/MoorhenMolecule.js
baby-gru/src/utils/MoorhenPreferences.js

This update adds "show maps as surfaces by default" and "default molecule bond smoothness" to the preferences menu. Also, a bug resulting from the interaction between `MoorhenMapCard` and `MoorhenSlider` that resulted in `get_map_contours_mesh` being called twice on map load has been fixed.

Add new entries to preferences and fix bug

---

baby-gru/src/components/MoorhenFillMissingAtoms.js
baby-gru/src/components/MoorhenKeyboardAccelerators.js
baby-gru/src/components/MoorhenMapCard.js
baby-gru/src/components/MoorhenPepflipsDifferenceMap.js
baby-gru/src/components/MoorhenSimpleEditButton.js
react-app/src/mgWebGL.js

This greatly simplifies some of the code in `MoorhenMapCard` by refactoring several event listeners that trigger a map re-contour into a single mapUpdate event. This also simplifies the code necessary to know when to pull rfactor/rail points from the api as there is only one event type now after a model update.

Refactor map event listeners into a single mapUpdate event

---

baby-gru/src/components/MoorhenMenuItem.js
baby-gru/src/components/MoorhenPepflipsDifferenceMap.js
baby-gru/src/components/MoorhenPreferencesMenu.js
baby-gru/src/components/MoorhenWebMG.js
baby-gru/src/utils/MoorhenPreferences.js

- Control for the scores that are shown after updating maps has been added to preferences.
- `sfcalc_genmaps_using_bulk_solvent` is used when connecting maps, which means scores are correct even before the first modification.

Control scores in preferences and use sfcalc_genmaps_using_bulk_solvent

---

baby-gru/src/components/MoorhenMapCard.js
baby-gru/src/utils/MoorhenMap.js

This implements the intended correct behaviour of the map sliders. Now, the map sliders will skip updates while busy. Then, if there is a pending update, it will be done after the current update is completed. This way playing with the contour level and radius sliders won't lock the app for so long.

Use recursion to skip map re-contours while busy

---

baby-gru/src/components/MoorhenMapCard.js
baby-gru/src/components/MoorhenMoleculeCard.js

Similar to #144 but with bond settings. This fixes a bug where playing with the bond smoothness and bond radius sliders would break the app if too many redraws are requested. Now only the most recent molecule redraw is requested (one at a time).

Only redraw molecule if not busy

---

baby-gru/src/components/MoorhenMapCard.js
baby-gru/src/components/MoorhenMenuItem.js
baby-gru/src/utils/MoorhenMap.js

This moves "activate lit lines" into the map display settings menu. Code to handle the combination of map surface + lit lines has been added (previously this would show a chickenwire map).

Update UI for map settings

---

baby-gru/src/utils/MoorhenMolecule.js

A patch for the change we discussed in slack. Waters are not ligands.

Waters are not ligands in drawCootRepresentation()

---

baby-gru/public/baby-gru/CootWorker.js
baby-gru/src/components/MoorhenAdvancedDisplayOptions.js
baby-gru/src/components/MoorhenContainer.js
baby-gru/src/components/MoorhenViewMenu.js
baby-gru/src/components/MoorhenWebMG.js
baby-gru/src/utils/MoorhenMolecule.js

This is a big update to the way the advanced display options are shown in the UI. The idea was to make them more compact so that they use less space. These options have been moved to the same toast container where the scores are shown after connecting maps. This new modal stays transparent so that the user can see the model, and only when hovered it will increase opacity. Additionally, the colour rules currently used for a given molecule are now listed.

Re-think advanced display options UI

---

baby-gru/src/components/MoorhenRamachandran.js

Ramachandran plot would not always highlight the hovered residue due to this.

Fix ramachandran bug caused by eqeqeq comparison

---

baby-gru/src/components/MoorhenKeyboardAccelerators.js
baby-gru/src/components/MoorhenMoleculeCard.js
baby-gru/src/components/MoorhenShortcutConfigModal.js
baby-gru/src/utils/MoorhenMolecule.js
baby-gru/src/utils/MoorhenPreferences.js
baby-gru/src/utils/MoorhenUtils.js
coot/moorhen-wrappers.cc

- Added `get_active_atom` to moorhen wrappers and wrapped its return type `int_string_pair` using `value_object`.
- Jump to next/previous residue has been added to shortcuts. By default they are binded to `Space` and `Shift+Space`. At the moment this always assumes the residue corresponds with the first chain (API function does not return chain name in the CID yet).
- The way shortcuts involving a "Space" are displayed in the UI has improved (now it shows `<Space>` instead of just an empty space).
- Contact dots and chemical features are filtered out from the checkboxes in the display options.
- A new `isVisible` attribute was added to `MoorhenMolecule` which is synced with its molecule card.
- A new `hasVisibleBuffers` was added to `MoorhenMolecule` and can be used …

Add jump to next/prev residue to shortcuts and other updates

---

baby-gru/cloud/index.js
baby-gru/src/WebGLgComponents/mgWebGL.js
baby-gru/src/components/MoorhenFileMenu.js
baby-gru/src/components/MoorhenHistoryMenu.js
baby-gru/src/components/MoorhenMenuItem.js
baby-gru/src/components/MoorhenWebMG.js
baby-gru/src/utils/MoorhenMolecule.js

After this update, removing the molecule or the map that was connected will make the score toast disappear. Also animations when centering on a molecule that was just loaded are turned off.

Hide score toast if connected molecule or map is deleted

---

baby-gru/src/components/MoorhenKeyboardAccelerators.js
baby-gru/src/components/MoorhenMoleculeCard.js
baby-gru/src/components/MoorhenPreferencesMenu.js
baby-gru/src/utils/MoorhenPreferences.js

This can be controlled using the preferences menu. At the moment this is only available with flip_peptide due to issues with the cid returned by `get_active_atom`

Enable shortcuts on the residue in the centre rather than hovered residue

---

baby-gru/src/components/MoorhenFileMenu.js
baby-gru/src/utils/MoorhenMolecule.js

This allows users to fetch models from the AFDB. PLDDT based color rules are not available yet.

Add AF2 models

---

baby-gru/src/components/MoorhenButtonBar.js
baby-gru/src/components/MoorhenContainer.js
baby-gru/src/components/MoorhenDifferenceMapPeaks.js
baby-gru/src/components/MoorhenKeyboardAccelerators.js
baby-gru/src/components/MoorhenMapCard.js
baby-gru/src/components/MoorhenMenuItem.js
baby-gru/src/components/MoorhenPepflipsDifferenceMap.js
baby-gru/src/components/MoorhenPreferencesMenu.js
baby-gru/src/components/MoorhenSlider.js

- Fix bug causing sliders at the clipping and fogging menu not to be set at the right value
- Update maps when using arrows to move the view
- Switch order of jed flip and add simple buttons as requested
- Rename display objects and take the checkboxes outside the accordion

Fix sliders and other updates

---

baby-gru/src/components/MoorhenPreferencesMenu.js
baby-gru/src/components/MoorhenWebMG.js
baby-gru/src/utils/MoorhenPreferences.js

This update simplifies the code in `MoorhenPreferences` so that it is possible to add more preferences without repeating so much code. This should avoid introduction of new bugs in the future. Also a control on whether the clipping and the fogging should be reset after zoom has been added to preferences.

Simplify moorhen preferences and add reset clipping/fogging after zoom

---

baby-gru/src/components/MoorhenColouRules.js
baby-gru/src/components/MoorhenFileMenu.js
baby-gru/src/utils/MoorhenMolecule.js
baby-gru/src/utils/MoorhenUtils.js

This adds the plddt colour rule, which is loaded by default into AF2 models. Additionally, the code to handle colour rules has been refactored into `MoorhenMolecule`.

Add plddt colour scheme and other changes

---

baby-gru/package.json
baby-gru/src/components/MoorhenLigandList.js
baby-gru/src/components/MoorhenMoleculeCard.js
baby-gru/src/utils/MoorhenMolecule.js

- Code related to fetching ligands has been refactored into `MoorhenMolecule` to make it more general
- Update UI for `MoorhenLigandList` so that they include a SVG representation of the ligand 
- Refactor code to include svg into the ligand cards. No longer use `dangerouslySetInnerHTML` and not necessary to keep cached gemmi structure in react component.

Refactor ligand card code and enable SVG

---

baby-gru/src/components/MoorhenCidInputForm.js
baby-gru/src/components/MoorhenColouRules.js
baby-gru/src/components/MoorhenSimpleEditButton.js

This update refactors the code for the CID input text form which is used in several places throughout the app. It also fixes the bug where the CID selection in the input box of the new rotate/translate custom button disappeared after hovering on a new atom.

Refactor cid input form

---

baby-gru/src/components/MoorhenContainer.js
baby-gru/src/components/MoorhenKeyboardAccelerators.js
baby-gru/src/components/MoorhenSimpleEditButton.js
baby-gru/src/utils/MoorhenTimeCapsule.js

This update connects the time capsule with the rest of the app. Now backups are done automatically after N modifications (default 5, user defined number to be added in the future). Oldest backup is removed when a threshold is hit (default 10, user defined value added to preferences in the future).

Automatic backups

---

baby-gru/src/components/MoorhenMapCard.js
baby-gru/src/components/MoorhenMenuItem.js
baby-gru/src/components/MoorhenMoleculeCard.js
baby-gru/src/components/MoorhenMoleculeCardButtonBar.js
baby-gru/src/components/MoorhenPreferencesMenu.js
baby-gru/src/components/MoorhenWebMG.js
baby-gru/src/utils/MoorhenUtils.js

- Fixed an issue with a window resize event listener
- Molecule and map names are omitted if they are longer than 10 characters. There's a tooltip that will appear on hover to show the full name
- Switched order of molecule card buttons as requested
- Moved switch to reset clipping/fogging on zoom to the VIew > Clipping/Fogging menu item

Minor changes to the UI and other fixes

---

baby-gru/src/components/MoorhenSimpleEditButton.js
coot/moorhen-wrappers.cc

- Random jiggle fit is added as a switch in the rigid body fit button
- Code in `MoorhenSimpleEditButton` has been extensively refactored to accommodate a new two click mode which can be used to define a residue range in the rigid body fit button

Enable two click mode for rigid body fit and enable random jiggle fit

---

baby-gru/src/components/MoorhenMoleculeCard.js
baby-gru/src/components/MoorhenSimpleEditButton.js
baby-gru/src/utils/MoorhenMolecule.js
baby-gru/src/utils/MoorhenUtils.js

This adds a selection style to `MoorhenMolecule`. Currently this is used to indicate what is the first residue selected for rigid body fitting.

Add selection style to molecule

---

baby-gru/public/baby-gru/CootWorker.js
baby-gru/src/components/MoorhenContainer.js
baby-gru/src/components/MoorhenFileMenu.js
baby-gru/src/utils/MoorhenMap.js
baby-gru/src/utils/MoorhenTimeCapsule.js
coot/moorhen-wrappers.cc

After this update, reflection data associated with a given map is also stored in the session backup. This means map can be re-connected after loading a backup.

Store reflection data in session backup

---

baby-gru/src/WebGLgComponents/mgWebGL.js
baby-gru/src/components/MoorhenKeyboardAccelerators.js
baby-gru/src/components/MoorhenNavBar.js
baby-gru/src/utils/MoorhenPreferences.js

This moves the shortcut help into HUD text that can be toggled on/off instead of a toast that disappears after a few seconds. Also the bird is back.

Show shortcut help as HUD instead of a toast

---

baby-gru/src/components/MoorhenKeyboardAccelerators.js
baby-gru/src/utils/MoorhenMolecule.js
baby-gru/src/utils/MoorhenUtils.js
coot/moorhen-wrappers.cc

After this update bond colours are set so that they follow the colour rules used for other representations. At the moment this is only implemented with colour rules affecting the whole molecule.

Set bond colours following colour rules of other representations

---

baby-gru/src/components/MoorhenMoleculeCard.js

This update fixes the bug where the initial state of molecule representation checkboxes is not set properly (bonds are not checked).

Fix molecule representation checkbox bug

---

baby-gru/cloud/MoorhenWrapper.js
baby-gru/cloud/index.html
baby-gru/src/components/MoorhenContainer.js
baby-gru/src/components/MoorhenFileMenu.js

Renamed `props.isCloud` to `props.disableFileUploads` and `props.exportToCloudCallback` to `props.exportCallback`. Function `exportToCloud` inside `MoorhenFileMenu.js` also renamed to `doExportCallback` which calls `props.exportCallback` if it has been provided. All of this infrastructure would then be available for other GUIs that might want to make use of it.

Make moorhen more GUI agnostic

---

baby-gru/src/components/MoorhenContextMenu.js
baby-gru/src/components/MoorhenSimpleEditButton.js
baby-gru/src/components/MoorhenWebMG.js

After this update, all the edit buttons found in the bottom button bar are also accessible in the context menu when a residue is selected.

Implement full set of edit buttons in the context menu

---

baby-gru/src/components/MoorhenFileMenu.js
baby-gru/src/components/MoorhenMenuItem.js
baby-gru/src/components/MoorhenWebMG.js
baby-gru/src/utils/MoorhenMolecule.js
baby-gru/src/utils/MoorhenTimeCapsule.js

After this update, when loading a backup moorhen will automatically connect molecules and maps that were connected in the loaded session.

Backlups store information about connected molecules and maps

---

baby-gru/cloud/MoorhenWrapper.js
baby-gru/src/components/MoorhenContainer.js
baby-gru/src/components/MoorhenFileMenu.js
baby-gru/src/components/MoorhenHistoryMenu.js
baby-gru/src/components/MoorhenMenuItem.js
baby-gru/src/utils/MoorhenMolecule.js
baby-gru/webpack.config.js

As requested for integration into cloud, after this update only a minimal monomer library and pixmaps are bundled with webpack when building the app and using `build-cloud`. Additionally, `MoorhenMolecule` will look for monomers in a folder passed via `props` to `MoorhenContainer`.

Only pack minimal monomer library and pixmaps

---

baby-gru/src/WebGLgComponents/mgWebGL.js
baby-gru/src/components/MoorhenKeyboardAccelerators.js
baby-gru/src/utils/MoorhenPreferences.js

After this update, the keyboard accelerators have changed to allow for a separate "label" atom and "measure" mode. To label an atom hold L & click (L = label). To measure distances, hold M & click (M = measure). I have made the list of labelled atoms and "measured" atom pairs independent from each other so it is possible to label a few atoms and then measure distances between another set of atoms. Hence, `clickedAtoms` has been renamed as `labelledAtoms` and a new list `measuredAtoms` was added to `mgWebGL`.

separate label atoms and measure atom distances

---

baby-gru/src/WebGLgComponents/mgWebGL.js
baby-gru/src/components/MoorhenContextMenu.js
baby-gru/src/components/MoorhenFillMissingAtoms.js
baby-gru/src/components/MoorhenKeyboardAccelerators.js
baby-gru/src/components/MoorhenMapCard.js
baby-gru/src/components/MoorhenMenuItem.js
baby-gru/src/components/MoorhenMoleculeCard.js
baby-gru/src/components/MoorhenPepflipsDifferenceMap.js
baby-gru/src/components/MoorhenSimpleEditButton.js
baby-gru/src/components/MoorhenWebMG.js
baby-gru/src/utils/MoorhenUtils.js

This fixes the issue where scores where out of step. The event `mapUpdate` has been renamed `scoreUpdate` and the only `mapUpdate` that involved change of origin has been refactored to use `originChange` instead.

Fix updating scores

---

baby-gru/src/App.js
baby-gru/src/components/MoorhenApp.js
baby-gru/src/components/MoorhenContainer.js

@martinemnoble1 as discussed, this update separates the code in `MoorhenContainer` into `MoorhenApp` (a new component) and `MoorhenContainer`. The latter can be replaced with a custom component in other UIs like i2 or cloud.

Move states and references defined in MoorhenContainer upstairs 

---

baby-gru/src/components/MoorhenButtonBar.js
baby-gru/src/components/MoorhenContainer.css

This fixes the issue where the carousel controls would sometimes overlap with the first half of the action buttons.

Fix overlapping carousel controls

---

baby-gru/src/components/MoorhenMenuItem.js
baby-gru/src/utils/MoorhenMolecule.js

After this update, the symmetry radius slider uses a recursive function to only draw the latest value of the slider.

Update symmetry slider to use recursion

---

baby-gru/cloud/src/components/MoorhenCloudApp.js
baby-gru/src/components/MoorhenContainer.js

@martinemnoble1 
As requested, after this update it is possible to overload the states and references defined in `MoorhenContainer`.

Overload states and refs of MoorhenContainer

---

baby-gru/cloud/src/components/MoorhenCloudApp.js
baby-gru/src/components/MoorhenChainSelect.js
baby-gru/src/components/MoorhenMenuItem.js
baby-gru/src/components/MoorhenMoleculeSelect.js
baby-gru/src/utils/MoorhenMolecule.js

This update fixes several issues:
- Empty menu in "centre on ligand" when there are no ligands
- Grey balls displayed in place of a ligand when using rotate translate and copy fragment
- SMILES with wrong format crash the app
- Grey ball ligands when importing a dictionary and not merging to a given molecule
- Import ligand will add the dictionary to all molecules instead of just the selected one
This update also includes UI elements for using conformers when using "Fit ligand here", but they will remain hidden until the "thread pool exhausted" issue is resolved.

Multiple fixes for ligand features

---

baby-gru/cloud/webcoot.html
baby-gru/public/index.html
react-app/public/index.html

The metadata displayed on Google underneath a search of Moorhen shows 'Web site created using create-react-app.', I have changed this to metadata to 'Moorhen is a molecular graphics web application based on the Coot desktop program.'

Updated meta data to better describe Moorhen

---

baby-gru/cloud/src/MoorhenWrapper.js
baby-gru/cloud/src/utils/MoorhenCloudTimeCapsule.js

This update fixes two bugs for ccp4 cloud:
- Time capsule fired twice during start up in cloud.
- MtzData backups contained a guid formatted as a file path.

Fix ccp4 cloud related bugs

---

baby-gru/public/manifest.json

Deployed version of Moorhen contains Create React App Boilerplate, I have changed this to better reflect the application (i.e. to Moorhen). 
Before
After

Changed default react app metadata to Moorhen

---

baby-gru/public/baby-gru/CootWorker.ts
baby-gru/src/components/button/MoorhenContextButtonBase.tsx
baby-gru/src/components/button/MoorhenDragAtomsButton.tsx
baby-gru/src/components/button/MoorhenRigidBodyFitButton.tsx
baby-gru/src/components/button/MoorhenRotateTranslateZoneButton.tsx
baby-gru/src/components/context-menu/MoorhenContextMenu.tsx
baby-gru/src/types/libcoot.d.ts

- Auto-clear atom pull restraints when dragging atoms can now be controlled by user input
- When using the context menu, when a draggable popover appears it will be rendered on one corner to not obstruct the view.
- Other cosmetic changes to context menu panels.
- Update superpose results parsing in cootWorker.

Add option to not auto-clear atom pull restraints and other requested changes
