stuartjamesmcnicholas/Moorhen

- baby-gru/src/components/BabyGruButtonBar.js
- baby-gru/src/components/BabyGruContainer.js
- baby-gru/src/components/BabyGruFileMenu.js
- baby-gru/src/components/BabyGruMoleculeUI.js
Two small changes to the UI:
- Now it should be possible to toggle on/off buttons on the left bar (auto-fit rotamer and flip peptide). Previously once a given button was clicked there was no option to cancel the operation (only choice was to select a residue). 
- The margins at the navbar and file input scrolldown menu were a bit off.
> Minor changes to UI

- baby-gru/src/components/BabyGruButtonBar.js
- baby-gru/src/components/BabyGruContainer.css
- baby-gru/src/components/BabyGruContainer.js
- baby-gru/src/components/BabyGruDensityFit.js
- baby-gru/src/components/BabyGruRamachandran.js
- react-app/src/Ramachandran.js
This update includes the following changes to the UI:
- Move sequence viewer and console viewer to side bar.
- Move button bar to the bottom of the screen.
- Contents of side bar are scrollable.
- Ramachandran plot dimensions are determined based on viewport dimensions. The plot also resizes when there are changes in window size.
> Fix ramachandran plot and update UI layout

- baby-gru/src/components/BabyGruDisplayObjects.js
- baby-gru/src/components/BabyGruSlider.js
With this update `BabyGruSlider` works out the initial value by itself.
> Set initial value for slider dinamically

- baby-gru/src/components/BabyGruButtonBar.js
- baby-gru/src/components/BabyGruContainer.js
- baby-gru/src/components/BabyGruFileMenu.js
- baby-gru/src/components/BabyGruMenuItem.js
This is just a minor addition to the UI, I have added the option to "delete everything" as requested on Friday. I have implemented the code using the new `BabyGruMenuItem`. Also button bar colour now will match the background colour of the visualisation panel.
> Enalbe delete everything

- baby-gru/src/components/BabyGruMenuItem.js
Sorry this was meant to go in the previous PR. This should let us set tutorial data more easily in the future rather than having to explicitly type the tutorial options.
> Set the tutorial options dinamically

- baby-gru/src/components/BabyGruContainer.js
- baby-gru/src/components/BabyGruMapCard.js
- baby-gru/src/components/BabyGruMoleculeCard.js
This sets the body of the molecule and the map cards as collapsible elements.
> Collapsible cards

- baby-gru/src/components/BabyGruDisplayObjects.js
- baby-gru/src/components/BabyGruMapCard.js
- baby-gru/src/components/BabyGruMoleculeCard.js
Same as #41 but for the dropdowns in molecule and map cards in the "Display Objects" accordion.
> Only show one dropdown at a time in display objects

- baby-gru/public/CootWorker.js
- baby-gru/src/components/BabyGruContainer.css
- baby-gru/src/components/BabyGruContainer.js
- baby-gru/src/components/BabyGruSequenceViewer.js
- baby-gru/src/components/BabyGruValidation.js
- baby-gru/src/utils/BabyGruUtils.js
This update enables the validation widget which is available inside the tools accordion.
> Validation widget

- baby-gru/public/CootWorker.js
- baby-gru/src/components/BabyGruChainSelect.js
- baby-gru/src/components/BabyGruContainer.js
- baby-gru/src/components/BabyGruRamachandran.js
- baby-gru/src/components/BabyGruValidation.js
This update includes the following changes to the validation plot:
- Text font changed to Helvetica
- Font size in the tooltips, axis labels and residue codes is proportional to plot dimensions and resizes with screen. At the moment it is set to fit ~40 bars in the horizontal dimension and ~60 characters in the available vertical space.
- Fixed abnormal density correlation values higher than 1
- Zoomed out default scale to include ~40 bars instead of 20
- If a chain without sequence data (such as ligands) is chosen, gracefully exit
- If molecule is deleted, gracefully remove plot
Also some changes to the ramachandran plot:
- If the chosen model is deleted, the plot is removed
- Fix issue where after last code update the plot was no longer updating upon changes to the molecule
> Several improvements to validation plot

- baby-gru/src/components/BabyGruChainSelect.js
- baby-gru/src/components/BabyGruContainer.css
- baby-gru/src/components/BabyGruContainer.js
- baby-gru/src/components/BabyGruMapSelect.js
- baby-gru/src/components/BabyGruMoleculeSelect.js
- baby-gru/src/components/BabyGruRamachandran.js
- baby-gru/src/components/BabyGruToolsAccordion.js
- baby-gru/src/components/BabyGruValidation.js
This update includes a new tools accordion with a search bar. Previously there was a tab approach to switch between different widgets, which could become a problem as we keep adding more widgets. Using this new layout it will be easier to add more widgets. The calculation of the height of the accordion body has been refactored so it should be more consistent across different tools.
> New tools accordion

- baby-gru/src/components/BabyGruMoleculeCard.js
- baby-gru/src/components/BabyGruToolsAccordion.js
- react-app/src/Ramachandran.js
This replaces the dropdown and search bar implemented using react-bootstrap in the tools accordion with a MUI `AutoComplete` component that can do the same within one component. This update changes contents of WebGL so it will be needed to do a new install.
> Replace tools accordion search bar with MUI component

- baby-gru/package.json
- baby-gru/public/baby-gru/CootWorker.js
- baby-gru/src/components/BabyGruDifferenceMapPeaks.js
- baby-gru/src/components/BabyGruMapSelect.js
- baby-gru/src/components/BabyGruToolsAccordion.js
- baby-gru/src/utils/BabyGruPreferences.js
- coot/moorhen-wrappers.cc
This update adds a widget to visualise difference map peaks to the tools accordion.
> Add difference map peaks widget to tools accordion

- baby-gru/public/baby-gru/CootWorker.js
- baby-gru/src/components/BabyGruDifferenceMapPeaks.js
- baby-gru/src/components/BabyGruRamachandran.js
- baby-gru/src/components/BabyGruSlider.js
- baby-gru/src/components/BabyGruValidation.js
After this update the data for the ramachandran plot is fetched from the libcoot api rather than the previous function defined in `moorhen-wrappers.cc`
> Update ramachandran plot to fetch data from libcoot api

- baby-gru/src/components/BabyGruMapCard.js
- baby-gru/src/components/BabyGruMoleculeCard.js
- baby-gru/src/utils/BabyGruMap.js
- baby-gru/src/utils/BabyGruPreferences.js
This makes the use of glRef consistent across all BabyGruMap functions. Two map deletion bugs have also been fixed. Description of the bugs from the project page:
Using data for tutorial 1:
~~A. If map no.1 is deleted then map no.2 becomes invisible. This is because the map contour and map level sliders are reset to weird values. If you touch the slider then you can see the map again.~~
A. After the update in PR #46, map no.2 no longer becomes invisible. Instead, now it will acquire the slider values of map no.1 which was just deleted.
B. If map no.2 is deleted, the the scene will not update until you interact with it (hovering with the mouse is enough).
> Small refactor and bug fix

- react-app/src/mgWebGL.js
This fixes exports errors after PR #63
> Fix export errors

- baby-gru/src/components/BabyGruPreferencesMenu.js
- baby-gru/src/components/BabyGruShortcutConfigModal.js
With this update a new UI element is added under the "Preferences" menu item to let users configure their own keyboard shortcuts.
> Enable user-defined shortcuts

- baby-gru/src/components/BabyGruShortcutConfigModal.js
- baby-gru/src/utils/BabyGruPreferences.js
This fixes the bug where default shortcuts were not re-stored correctly.
> Ffix restore default preferences bug

- baby-gru/src/components/BabyGruContainer.js
- baby-gru/src/components/BabyGruPreferencesMenu.js
- baby-gru/src/components/BabyGruSlider.js
- baby-gru/src/components/BabyGruWebMG.js
- baby-gru/src/utils/BabyGruPreferences.js
- react-app/src/mgWebGL.js
After this update users can set their own mouse sensitivity which is stored in the persistent preferences.
> Add mouse sensitivity to preferences

- baby-gru/src/components/BabyGruRamachandran.js
- baby-gru/src/components/BabyGruShortcutConfigModal.js
- baby-gru/src/utils/BabyGruPreferences.js
- react-app/src/Ramachandran.js
I forgot to add the new preferences to the `collectedprops` in PR #74
> Minor bug fix and connect rama plot with hoveredAtom

- baby-gru/src/components/BabyGruContainer.js
- baby-gru/src/components/BabyGruMenuItem.js
- baby-gru/src/components/BabyGruPreferencesMenu.js
- baby-gru/src/components/BabyGruSearchBar.js
- baby-gru/src/components/BabyGruSimpleEditButton.js
This adds a search bar to the navbar. With this search bar it is possible to search for actions and the UI will take the necessary steps to activate said action. I think this could be helpful for first-time users. At the moment there are only a few options available as this is more of a test to see if we like this or if we think it's useless. If we like this it should be trivial to implement more actions.
> Enable search bar 

- baby-gru/src/components/BabyGruMenuItem.js
After this update it is possible to add ligands fetched from MRC-LMB
> Enable download of ligand from MRC-LMB

- baby-gru/src/components/BabyGruMenuItem.js
Minor fix related to the way menu options are handled after #88 and the response status from MRC-LMB
> Minor bug fix

- baby-gru/src/components/BabyGruFileMenu.js
- baby-gru/src/components/BabyGruMapCard.js
- baby-gru/src/utils/BabyGruMap.js
After this update map data is also stored in the session json file.
> Enable map storage in session json

- baby-gru/src/components/BabyGruMoleculeCard.js
After this update, a list of ligands contained in a given molecule is listed in its display card. There's a "View" button that will center the view on the ligand.
> List ligands in molecule card

- baby-gru/src/components/BabyGruLigandList.js
- baby-gru/src/components/BabyGruMoleculeCard.js
This update moves the code to create the ligand list to a separate component and fixes the bug where the app crashes if a ligand is deleted from a molecule.
> Refactor cde and minor ligand bug fix

- baby-gru/package.json
- baby-gru/src/App.js
- baby-gru/src/components/BabyGruContainer.js
- baby-gru/src/components/BabyGruMapCard.js
- baby-gru/src/components/BabyGruMenuItem.js
- baby-gru/src/components/BabyGruSimpleEditButton.js
- baby-gru/src/utils/BabyGruUtils.js
This will update the url of all assets to include a root homepage determined by props passed to `BabyGruContainer`. The default value of this prop is set to  `"."` so it will need to be set to an empty string in your code @martinemnoble1
> Add url prefix to props

- baby-gru/cloud/index.html
- baby-gru/cloud/index.js
- baby-gru/src/components/MoorhenCloudMenu.js
- baby-gru/src/components/MoorhenContainer.js
This update enables a new menu item used in the context of ccp4 cloud to export data using a custom event.
> Add cloud export menu item

- baby-gru/src/components/MoorhenChainSelect.js
- baby-gru/src/components/MoorhenMenuItem.js
- baby-gru/src/components/MoorhenRamachandran.js
- baby-gru/src/components/MoorhenSequenceViewer.js
- baby-gru/src/components/MoorhenValidation.js
- baby-gru/src/utils/MoorhenMolecule.js
- baby-gru/src/utils/MoorhenUtils.js
- react-app/src/Ramachandran.js
This update includes more changes to move away from `mgMinMol` to parse molecule sequences
> More changes to use gemmi sequence

- baby-gru/src/components/MoorhenContainer.css
- baby-gru/src/components/MoorhenContainer.js
- baby-gru/src/components/MoorhenFileMenu.js
- baby-gru/src/components/MoorhenHelpMenu.js
- baby-gru/src/components/MoorhenHistoryMenu.js
- baby-gru/src/components/MoorhenPreferencesMenu.js
- baby-gru/src/components/MoorhenSearchBar.js
- baby-gru/src/components/MoorhenViewMenu.js
- react-app/src/mgWebGL.js
Some minor aesthetic changes to the UI
- Scrollbar is now hidden in firefox (this was causing problems in windows)
- Crosshais size reduced by a factor of 3
- Search bar has been moved to a new Help menu in the navbar. This could contain more items in the future (tutorials, what's new...etc)
- Added horizontal lines within navbar dropdown menus (I think it facilitates navigation)
> Minor aesthetic changes

- baby-gru/package-lock.json
- coot/CMakeLists.txt
- coot/moorhen-wrappers.cc
One is the package-lock.json. I wanted it get it out of the way.
Second is the changes to the CMakeLists.txt and wrapper to get coot to compile after recent updates.
When this works, I will make functions to get the meshes for the chemical features and gaussian surfaces.
OK gaussian surfaces have been added - they need an extra file to be compiled.
> Two changes... 

- baby-gru/src/utils/MoorhenMolecule.js
- baby-gru/src/utils/MoorhenUtils.js
Same as #112 but now also `MoorhenMolecule.drawCootBonds`
> Draw coot bonds using gemmi

- baby-gru/src/utils/MoorhenMolecule.js
- baby-gru/src/utils/MoorhenUtils.js
This fixes the bug observed for PDB entry 1JST where the sequences could not be parsed.
> Fix sequence viewer bug

- baby-gru/src/components/MoorhenSequenceViewer.js
- baby-gru/src/utils/MoorhenMolecule.js
After this update the label of modified residues is shown correctly when hovering on the sequence viewer.
> Minor changes to sequence viewer

- baby-gru/src/components/MoorhenFileMenu.js
This update makes map downloads optional when fetching a structure from the PDBe or the PDB-REDO
> Optional download map when fetching structure

- baby-gru/cloud/index.html
- baby-gru/public/index.html
- baby-gru/src/components/MoorhenFileMenu.js
- baby-gru/src/components/MoorhenMoleculeCardButtonBar.js
- baby-gru/src/components/MoorhenPreferencesMenu.js
This update deals with some minor issues found when using windows and small laptops.
> Setup scroll bars to deal with windows and small laptops

- baby-gru/src/components/MoorhenChainSelect.js
- baby-gru/src/utils/MoorhenMolecule.js
- baby-gru/src/utils/MoorhenUtils.js
This fixes the memory leak observed when modifying molecules
> Fix memory leak

- baby-gru/src/utils/MoorhenMolecule.js
- baby-gru/src/utils/MoorhenUtils.js
This improves memory management of emscriptem objects.
> Some emscriptem improvements

- baby-gru/public/baby-gru/CootWorker.js
This might help reducing the memory issues @stuartjamesmcnicholas
> Possibly non-leaking mesh to data

- baby-gru/src/components/MoorhenLigandList.js
- baby-gru/src/components/MoorhenMenuItem.js
- baby-gru/src/components/MoorhenSequenceViewer.js
- baby-gru/src/utils/MoorhenMolecule.js
- baby-gru/src/utils/MoorhenUtils.js
- react-app/src/gemmiAtomsToPrimitives.js
This fixes multiple memory leaks across different parts of the app (I hope).
> Fix multiple memory leaks

- react-app/src/mgWebGL.js
Down to 0.3 - that seems about right too me .
> Scale down the cross-hairs some more

- baby-gru/src/components/MoorhenButtonBar.js
- baby-gru/src/components/MoorhenSimpleEditButton.js
- coot/moorhen-wrappers.cc
This update includes the following:
- "Mutate residue" button will run auto-fit rotamer when done
- Fill partial residue has been added to the button bar. The button doesn't contain an icon yet.
- Add alternative conformation has been added, but it's yet not available as there seem to be some issues with the returned mesh data
> New buttons

- baby-gru/src/components/MoorhenFillMissingAtoms.js
- baby-gru/src/components/MoorhenKeyboardAccelerators.js
- baby-gru/src/components/MoorhenMapCard.js
- baby-gru/src/components/MoorhenMenuItem.js
- baby-gru/src/components/MoorhenMoleculeCard.js
- baby-gru/src/components/MoorhenPepflipsDifferenceMap.js
- baby-gru/src/components/MoorhenSimpleEditButton.js
- baby-gru/src/components/MoorhenWebMG.js
- react-app/src/mgWebGL.js
After this update, a toast with moorhen points and Rfactor is shown after connecting maps. Modifications to the model will trigger recalculation of scores, which will be highlighted in green/red depending on whether they improved or not.
> Enable gru points and rFactor/rFree

- baby-gru/src/components/MoorhenMapCard.js
This was meant to go with #144
> Follow-up to previous PR

- baby-gru/src/components/MoorhenAdvancedDisplayOptions.js
This adds the ability to create color rules with a residue CID
> Add colour rules using residue CIDs

- README.md
This includes the update in #150
> Update master with build-test-2

- baby-gru/src/components/MoorhenAdvancedDisplayOptions.js
- baby-gru/src/components/MoorhenSimpleEditButton.js
- baby-gru/src/utils/MoorhenUtils.js
This update adds tooltips to the new advanced display options menu and adds shortcut labels to the tooltips in the bottom button bar.
> Add tooltips with shortcuts

- baby-gru/src/components/MoorhenEditMenu.js
- baby-gru/src/components/MoorhenMenuItem.js
- baby-gru/src/components/MoorhenWebMG.js
- coot/moorhen-wrappers.cc
The new menu item is in Edit > Add/Remove hydrogens
> Add add/delete H to the UI

- baby-gru/src/components/MoorhenEditMenu.js
- baby-gru/src/components/MoorhenMenuItem.js
- baby-gru/src/components/MoorhenSequenceViewer.js
- baby-gru/src/utils/MoorhenPreferences.js
After this update, the sequence viewer will update after a residue is mutated/added/removed.
> Update sequence viewer after modifications to the sequence

- baby-gru/package.json
- baby-gru/public/baby-gru/CootWorker.js
- baby-gru/src/components/MoorhenMMRRCCPlot.js
- baby-gru/src/components/MoorhenToolsAccordion.js
This adds a new widget to create the MMRRCC plot. Unlike other widgets, clicking a button is required to create the plot as it takes several seconds and users might want to be able to decide when to refresh the plot.
> Add MMRRCC plot

- baby-gru/src/WebGLgComponents/mgWebGL.js
- baby-gru/src/utils/MoorhenMolecule.js
Following @stuartjamesmcnicholas patch
> Do not re-render map during animations

- baby-gru/src/components/MoorhenKeyboardAccelerators.js
This now uses the correct residue CID
> Fix spacebar to jump next residue

- baby-gru/cloud/index.html
- baby-gru/cloud/index.js
- baby-gru/package.json
- baby-gru/src/components/MoorhenCloudMenu.js
- baby-gru/src/components/MoorhenContainer.js
- baby-gru/src/components/MoorhenDifferenceMapPeaks.js
- baby-gru/src/components/MoorhenFillMissingAtoms.js
- baby-gru/src/components/MoorhenPepflipsDifferenceMap.js
- baby-gru/src/components/MoorhenValidation.js
This update includes some small changes requested for the app:
- Moorhen cloud wrapper now takes a callback function to export data
- View and Flip buttons have been switched order. Same with the Fill missing atoms widget.
- Waterfall plot order has been reversed (first positive peaks then negatives). A horizontal line at 0 has been added
- Validation plots now contain a horizontal line at 0
- The border thickness of the bars in the validation plot and the waterfall plot is set relative to the screen width.
> Several minor changes

- baby-gru/src/components/MoorhenContainer.js
- baby-gru/src/components/MoorhenFillMissingAtoms.js
- baby-gru/src/components/MoorhenLigandList.js
- baby-gru/src/components/MoorhenMapCard.js
- baby-gru/src/components/MoorhenMoleculeCard.js
- baby-gru/src/components/MoorhenPepflipsDifferenceMap.js
- baby-gru/src/components/MoorhenRamachandran.js
- baby-gru/src/components/MoorhenToolsAccordion.js
Use of smaller margins will benefit users with narrower displays
> Use less margins between components

- baby-gru/src/components/MoorhenMenuItem.js
The new menu item is under Edit > Superpose structures.
> Add ssm superpose

- baby-gru/src/components/MoorhenBackupSelect.js
- baby-gru/src/components/MoorhenContainer.js
- baby-gru/src/components/MoorhenFileMenu.js
- baby-gru/src/components/MoorhenMenuItem.js
- baby-gru/src/utils/MoorhenTimeCapsule.js
After this update all the code required to manage stored backups has been refactored into `MoorhenTimeCapsule`. At the moment this new implementation doesn't bring new functionalities, it only matches those already present in the previous code. Future updates will include new functionalities, like auto-backup every N modifications (should be trivial as `MoorhenTimeCapsule` keeps a modification counter).
> Add MoorhenTimeCapsule

- baby-gru/src/components/MoorhenMenuItem.js
- baby-gru/src/components/MoorhenPreferencesMenu.js
- baby-gru/src/components/MoorhenSlider.js
- baby-gru/src/utils/MoorhenPreferences.js
- baby-gru/src/utils/MoorhenTimeCapsule.js
User defined settings for the time capsule
> Set backup controls in preferences

- baby-gru/src/components/MoorhenBackupSelect.js
- baby-gru/src/components/MoorhenFileMenu.js
- baby-gru/src/components/MoorhenMenuItem.js
- baby-gru/src/utils/MoorhenTimeCapsule.js
After this update two different kinds of backups are created. There are manual and there are automatic. A manual backup won't be deleted when the maximum number of automatic backups is reached. Manual backups can be named.
> Separate manual and auto backups

- baby-gru/src/components/MoorhenBackupSelect.js
- baby-gru/src/components/MoorhenFileMenu.js
- baby-gru/src/components/MoorhenMenuItem.js
- baby-gru/src/utils/MoorhenTimeCapsule.js
This greatly simplifies the code use to store and retrieve backups by storing everything in the same storage instance and using objects as keys.
> Simplify backups code

- baby-gru/src/components/MoorhenBackupSelect.js
- baby-gru/src/components/MoorhenDifferenceMapPeaks.js
- baby-gru/src/components/MoorhenFileMenu.js
- baby-gru/src/components/MoorhenMenuItem.js
- baby-gru/src/components/MoorhenWebMG.js
- baby-gru/src/utils/MoorhenTimeCapsule.js
- baby-gru/src/utils/MoorhenUtils.js
- Enable backup deletion
- Add peak index in the waterfall plot
- 10% less colour for the plddt colour palette
- Fix for the bug where the clipping and the fogging reset on window resize even if the user chose not to reset them on zoom
> Backup deletion and feature requests

- baby-gru/src/utils/MoorhenMolecule.js
This removes some repeated code after #194
> Refactor repeated code

- baby-gru/src/components/MoorhenSimpleEditButton.js
Fix a bug that prevented buttons in the bottom bar from working after #193
> JSON bug fix

- baby-gru/src/components/MoorhenButtonBar.js
- baby-gru/src/components/MoorhenConsole.js
- baby-gru/src/components/MoorhenContainer.js
- baby-gru/src/components/MoorhenDifferenceMapPeaks.js
- baby-gru/src/components/MoorhenDisplayObjects.js
- baby-gru/src/components/MoorhenEditMenu.js
- baby-gru/src/components/MoorhenFileMenu.js
- baby-gru/src/components/MoorhenFillMissingAtoms.js
- baby-gru/src/components/MoorhenHelpMenu.js
- baby-gru/src/components/MoorhenHistoryMenu.js
- baby-gru/src/components/MoorhenLigandMenu.js
- baby-gru/src/components/MoorhenMMRRCCPlot.js
- baby-gru/src/components/MoorhenMenuItem.js
- baby-gru/src/components/MoorhenPepflipsDifferenceMap.js
- baby-gru/src/components/MoorhenPreferencesMenu.js
- baby-gru/src/components/MoorhenRamachandran.js
- baby-gru/src/components/MoorhenSideBar.js
- baby-gru/src/components/MoorhenToolsAccordion.js
- baby-gru/src/components/MoorhenValidation.js
- baby-gru/src/components/MoorhenViewMenu.js
This update includes a new UI layout based on the use of more MUI components and drawers.
> New UI layout

- baby-gru/package.json
- baby-gru/src/WebGLgComponents/mgWebGL.js
- baby-gru/src/components/MoorhenButtonBar.js
- baby-gru/src/components/MoorhenContainer.js
- baby-gru/src/components/MoorhenContextMenu.js
- baby-gru/src/components/MoorhenSideBar.js
- baby-gru/src/components/MoorhenWebMG.js
- baby-gru/src/utils/MoorhenPreferences.js
This update adds a context menu that can be opened using right click. It also fixes the following:
- Buttons to collapse the drawers were not rendered as intended on a dark background
- Background color selector breaks when selecting different colors quickly
> UI fixes and context menu

- baby-gru/src/components/MoorhenContainer.js
- baby-gru/src/components/MoorhenContextMenu.js
- baby-gru/src/components/MoorhenDisplayObjects.js
- baby-gru/src/components/MoorhenMenuItem.js
- baby-gru/src/components/MoorhenWebMG.js
This adds "Connect map and molecule" and "Create backup" to the context menu.
> Add more items to context menu

- baby-gru/src/components/MoorhenContainer.css
- baby-gru/src/components/MoorhenContainer.js
- baby-gru/src/components/MoorhenContextMenu.js
- baby-gru/src/components/MoorhenEditMenu.js
- baby-gru/src/components/MoorhenFileMenu.js
- baby-gru/src/components/MoorhenHelpMenu.js
- baby-gru/src/components/MoorhenHistoryMenu.js
- baby-gru/src/components/MoorhenLigandMenu.js
- baby-gru/src/components/MoorhenMenuItem.js
- baby-gru/src/components/MoorhenNavBar.js
- baby-gru/src/components/MoorhenPreferencesMenu.js
- baby-gru/src/components/MoorhenSideBar.js
- baby-gru/src/components/MoorhenViewMenu.js
After the UI goes back to the classic top bar menu layout. The new button bar and side bar have been retained and the navbar has been made shorter.
> Go back to top bar layout

- baby-gru/src/components/MoorhenButtonBar.js
- baby-gru/src/components/MoorhenMapCard.js
- baby-gru/src/components/MoorhenMoleculeCard.js
- baby-gru/src/components/MoorhenPreferencesMenu.js
- baby-gru/src/components/MoorhenSideBar.js
- baby-gru/src/components/MoorhenSimpleEditButton.js
- baby-gru/src/components/MoorhenViewMenu.js
This update should make the calculations for the size of the button bar and the side bar more consistent
> Improve calculations for side bar and button bar dimensions

- baby-gru/src/components/MoorhenContainer.js
- baby-gru/src/components/MoorhenContextMenu.js
- baby-gru/src/components/MoorhenSimpleEditButton.js
- baby-gru/src/components/MoorhenWebMG.js
A set of quick action buttons has been added to the context menu. This are similar to the simple edit buttons in the bottom bar. Some buttons are still missing and might arrive in the future.
> Add quick actions to context menu

- baby-gru/src/components/MoorhenContextMenu.js
The context menu is now aware of screen dimensions and it will position itself and any other popover accordingly so that they fit the screen.
> Minor changes to context menu

- baby-gru/cloud/MoorhenWrapper.js
- baby-gru/src/components/MoorhenFileMenu.js
- baby-gru/src/components/MoorhenMapCard.js
- baby-gru/src/components/MoorhenMenuItem.js
After this update maps will adjust their contour to match the previous rmsd before connecting.
> Adjust contour after connecting maps

- baby-gru/src/components/MoorhenContainer.js
- baby-gru/src/components/MoorhenSimpleEditButton.js
This fixes the bug where the map doesn't update after Add simple is used.
> Update map and scores after add simple

- baby-gru/src/components/MoorhenButtonBar.js
- baby-gru/src/components/MoorhenColourRules.js
- baby-gru/src/components/MoorhenContainer.css
- baby-gru/src/components/MoorhenMenuItem.js
- baby-gru/src/components/MoorhenSideBar.js
After this update, scroll bars are displayed in some of the UI components. This update also includes a bug fix for the context menu "Get monomer" button.
> Bring back scrollbars to some components and bug fix

- baby-gru/cloud/MoorhenWrapper.js
- baby-gru/public/baby-gru/CootWorker.js
- baby-gru/src/utils/MoorhenMolecule.js
This update adds necessary functions to update a given molecule with the contents of a file. This will be operational once the corresponding function is exposed in the api.
> Add functions to update molecule with file contents

- baby-gru/cloud/MoorhenWrapper.js
- baby-gru/cloud/webcoot.html
- baby-gru/webpack.config.js
This update includes the following fixes for cloud:
- `setTimeout` is used instead of `setInterval` to fetch molecule updates
- The file `webcoot.html` is included in the build folder
- The css file is not renamed after every update.
> Fixes for cloud build

- baby-gru/cloud/webcoot.html
- baby-gru/src/components/MoorhenSequenceViewer.js
This fixes a bug where protvista elements are defined twice when running in cloud.
> Fix DOMException in cloud

- baby-gru/public/baby-gru/CootWorker.js
- baby-gru/src/components/MoorhenSimpleEditButton.js
- baby-gru/src/components/MoorhenWebMG.js
- baby-gru/src/utils/MoorhenMap.js
- baby-gru/src/utils/MoorhenMolecule.js
After this update debug timings are printed synchronously and conversion timings are also included.
> Print timings synchronously

- baby-gru/src/components/MoorhenHelpMenu.js
This adds a button to simulate 100 peptide flips and print timings.
> Add test button

- baby-gru/cloud/MoorhenWrapper.js
- baby-gru/src/components/MoorhenContainer.js
- baby-gru/src/components/MoorhenContextMenu.js
- baby-gru/src/components/MoorhenKeyboardAccelerators.js
- baby-gru/src/components/MoorhenMapCard.js
- baby-gru/src/components/MoorhenWebMG.js
- baby-gru/src/utils/MoorhenKeyboardAccelerators.js
- baby-gru/src/utils/MoorhenMolecule.js
- baby-gru/src/utils/MoorhenPreferences.js
This update includes bug fixes for cloud:
- Shortcuts and a context menu to set background color are shown in view-only mode.
- Molecule update interval doesn't crash if the input file cannot be fetched.
- Map update events (origin, contour level and radius) now work.
> Several updates for cloud view-only mode based on feedback

- baby-gru/cloud/MoorhenCloudApp.js
- baby-gru/cloud/MoorhenLegendToast.js
- baby-gru/cloud/MoorhenWrapper.js
- baby-gru/src/WebGLgComponents/mgWebGL.js
- baby-gru/src/utils/MoorhenKeyboardAccelerators.js
After this update, a toast with model building stats is added to the view-only mode in cloud
> Set a toast with model building stats in cloud view-only mode

- baby-gru/src/components/MoorhenButtonBar.js
- baby-gru/src/components/MoorhenContextMenu.js
- baby-gru/src/components/MoorhenMenuItem.js
- baby-gru/src/components/MoorhenSimpleEditButton.js
- baby-gru/webpack.config.js
- coot/moorhen-wrappers.cc
After this update it is possible to switch between different rotamers using the button bar and the context menu.
> Add "next rotamer" to button bar and context menu

- baby-gru/cloud/src/MoorhenWrapper.js
- baby-gru/cloud/src/components/MoorhenCloudApp.js
- baby-gru/cloud/src/utils/MoorhenCloudTimeCapsule.js
- baby-gru/src/components/MoorhenContainer.js
- baby-gru/src/utils/MoorhenTimeCapsule.js
- baby-gru/src/utils/MoorhenUtils.js
This update provides the necessary code to enable backups in CCP4 cloud.
> Enable CCP4 cloud backups

- baby-gru/cloud/src/MoorhenWrapper.js
- baby-gru/cloud/src/components/MoorhenCloudApp.js
- baby-gru/cloud/src/utils/MoorhenCloudTimeCapsule.js
- baby-gru/src/components/MoorhenBackupSelect.js
- baby-gru/src/components/MoorhenContextMenu.js
- baby-gru/src/components/MoorhenFileMenu.js
- baby-gru/src/utils/MoorhenTimeCapsule.js
This update includes more changes required to make the time capsule backups functional in ccp4 cloud.
> Updates to CCP4 cloud backup storage

- baby-gru/src/components/MoorhenPreferencesMenu.js
- baby-gru/src/components/MoorhenWebMG.js
- baby-gru/src/utils/MoorhenPreferences.js
Related to #291, change map thickness as requested.
> Actually map thickness was requested to 0.75

- baby-gru/src/components/MoorhenButtonBar.js
- baby-gru/src/components/MoorhenContextMenu.js
- baby-gru/src/components/MoorhenSimpleEditButton.js
- coot/moorhen-wrappers.cc
This update includes the following changes to the next rotamer button:
- Previous / Next rotamer buttons added
- Go to first rotamer added
- Name and rank of current rotamer displayed
> Changes to next rotamer button

- baby-gru/src/components/MoorhenContextMenu.js
- baby-gru/src/components/MoorhenFileMenu.js
- baby-gru/src/components/MoorhenMenuItem.js
- web_example/CMakeLists.txt
This update fixes a bug preventing the app from reading coord cif files and fetching PDBe entries where only cif files are available.
> Fix coord cif related bugs

- baby-gru/src/components/MoorhenMenuItem.js
- baby-gru/src/utils/MoorhenKeyboardAccelerators.js
This update fixes a bug where importing a dictionary when there are no molecules loaded doesn't work.
> Fix import dictionary bug

- baby-gru/src/components/MoorhenContainer.js
- baby-gru/src/components/MoorhenMapCard.js
- baby-gru/src/components/MoorhenSlider.js
- baby-gru/src/utils/MoorhenKeyboardAccelerators.js
This update includes some cosmetic changes to the map card and a toast showing the current map contour level as requested.
> Cosmetic changes to map card and contour level toast

- baby-gru/src/components/MoorhenMapCard.js
- baby-gru/src/components/MoorhenSlider.js
This update fixes the issue where changing the map radius or contour using shortcuts won't update the slider value.
> Fix map slider bug

- baby-gru/src/ErrorBoundary.js
- baby-gru/src/components/MoorhenFileMenu.js
- baby-gru/src/components/MoorhenMenuItem.js
- baby-gru/src/components/MoorhenMoleculeCard.js
This fixes the following issues as requested:
- Bond smoothness settings are not loaded correctly when loading a backup session.
- Error boundary button not working
- Light and fogging menu too wide and obscure view
> Fix some minor issues

- baby-gru/public/keyboard-blank.svg
- baby-gru/src/components/MoorhenControlsModal.js
- baby-gru/src/components/MoorhenHelpMenu.js
- blog/_posts/2023-03-22-Moorhen-Tutorial-1.md
- coot/CMakeLists.txt
This update adds a menu item under the Help menu that can be used to show moorhen controls.
> Add "show moorhen controls" modal

- baby-gru/cloud/src/components/MoorhenCreateAcedrgLinkModal.js
- baby-gru/src/components/modal/KetcherModal.js
- baby-gru/webpack.config.js
This update improves the time spent on start up by refactoring the code in the new ketcher modal. It also includes other fixes for cloud.
> Reduce start-up time and some fixes for cloud

- baby-gru/cloud/src/MoorhenWrapper.js
This fixes the bug that crashed the app when loading a ligand using inputFiles in cloud.
> Fix bug caused when loading a ligand into cloud

- .github/workflows/tsc-compilation.yml
- baby-gru/package.json
- baby-gru/src/App.tsx
This update adds a github workflow to test typescript compilation after every commit.
> Add workflow to test tsc compilation

- baby-gru/src/WebGLgComponents/mgWebGL.js
- baby-gru/src/components/MoorhenApp.tsx
- baby-gru/src/types/index.d.ts
- baby-gru/src/utils/MoorhenKeyboardAccelerators.tsx
- baby-gru/src/utils/MoorhenMap.ts
- baby-gru/src/utils/MoorhenMolecule.ts
- baby-gru/src/utils/MoorhenPreferences.tsx
- baby-gru/src/utils/MoorhenTimeCapsule.ts
After this update all contents of `src/utils` uses TS
> Migrate all src/utils to TS

- baby-gru/cloud/src/MoorhenWrapper.js
This fixes a bug in CCP4 cloud where moorhen fails to start if the molecule file is not present at the beginning
> Fix bug in cloud view-update mode

- baby-gru/public/baby-gru/CootWorker.js
- baby-gru/src/WebGLgComponents/mgWebGL.js
- baby-gru/src/components/MoorhenContainer.tsx
- baby-gru/src/components/button/MoorhenButtonBar.js
- baby-gru/src/components/button/MoorhenSimpleEditButton.js
- baby-gru/src/components/context-menu/MoorhenContextMenu.js
- baby-gru/src/components/navbar-menus/MoorhenDevMenu.tsx
- baby-gru/src/components/navbar-menus/MoorhenFileMenu.tsx
- baby-gru/src/components/validation-tools/MoorhenFillMissingAtoms.js
- baby-gru/src/components/validation-tools/MoorhenPepflipsDifferenceMap.js
- baby-gru/src/types/index.d.ts
- baby-gru/src/utils/MoorhenKeyboardAccelerators.tsx
- baby-gru/src/utils/MoorhenMap.ts
- baby-gru/src/utils/MoorhenMolecule.ts
- baby-gru/src/utils/MoorhenTimeCapsule.ts
- baby-gru/src/utils/MoorhenUtils.ts
- coot/moorhen-wrappers.cc
This implements dragging atoms button.
> Dragging atoms

- baby-gru/src/types/index.d.ts
- baby-gru/src/utils/MoorhenMolecule.ts
This fixes issue with rotate/translate and change rotamer
> Fix bug when parsing CIDs with gemmi

- baby-gru/src/components/modal/MoorhenQuerySequenceModal.tsx
- baby-gru/src/components/navbar-menus/MoorhenFileMenu.tsx
This update adds a menu item under the File menu to query the PDB for entries sharing a user-defined sequence identity threshold.
> Add a menu item to fetch PDB entries based on current sequence

- baby-gru/src/components/modal/MoorhenQuerySequenceModal.tsx
- baby-gru/src/components/navbar-menus/MoorhenFileMenu.tsx
- baby-gru/src/utils/MoorhenMolecule.ts
- baby-gru/src/utils/MoorhenTimeCapsule.ts
Updates the component introduced in #384 to allow users to query AFDB models.
> Update menu item to allow sequence queries to AFDB

- baby-gru/src/components/menu-item/MoorhenMoleculeSymmetrySettingsMenuItem.tsx
- baby-gru/src/types/gemmi.d.ts
- baby-gru/src/types/libcoot.d.ts
- baby-gru/src/utils/MoorhenMolecule.ts
- baby-gru/src/utils/MoorhenUtils.ts
- coot/gemmi-wrappers.cc
Continuation of #370, but now it works.
> Enable draw unit cell

- baby-gru/src/components/card/MoorhenMoleculeCard.tsx
- baby-gru/src/components/list/MoorhenLigandList.tsx
- baby-gru/src/components/menu-item/MoorhenMoleculeSymmetrySettingsMenuItem.tsx
- baby-gru/src/utils/MoorhenMolecule.ts
This update fixes #388 and other issues related with the unit cell not disappearing after switching it off.
> Fix ligand SVG viewbox  

- baby-gru/cloud/src/MoorhenWrapper.tsx
- baby-gru/src/components/card/MoorhenMapCard.tsx
- baby-gru/src/types/moorhen.d.ts
- baby-gru/src/utils/MoorhenMap.ts
> Allow users to setup difference map colours

- baby-gru/src/components/modal/MoorhenColourRules.js
- baby-gru/src/components/modal/MoorhenCreateAcedrgLinkModal.tsx
- baby-gru/src/components/modal/MoorhenQuerySequenceModal.tsx
- baby-gru/src/components/modal/MoorhenScriptModal.tsx
This update fixes several DOM warnings thrown when the app starts.
> Fix warnings "findDOMNode is deprecated in StrictMode" on start-up
